#
# Copyright (C) 2020 The MoKee Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD_VENDOR := apple

COMMON_PATH := device/apple/t8010-common

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

TARGET_USES_64_BIT_BINDER := true

# APEX
TARGET_FLATTEN_APEX := true

# Audio
AUDIOSERVER_MULTILIB := 64
USE_XML_AUDIO_POLICY_CONF := 1

# Bootloader
TARGET_NO_BOOTLOADER := true

# HIDL
DEVICE_MANIFEST_FILE := $(COMMON_PATH)/manifest.xml

# Kernel
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 0x4000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_IMAGE_NAME := Image.lzma

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/apple/t8010
TARGET_KERNEL_CONFIG := mokee_t8010_defconfig

BOARD_KERNEL_SEPARATED_DT := true
BOARD_DTBTOOL_ARGS := -d D10,D101,D11,D111,N112
TARGET_CUSTOM_DTBTOOL := dtbToolApple

# Media
TARGET_ENABLE_MEDIADRM_64 := true

# Partitions
BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true
BOARD_SUPER_PARTITION_SIZE := 3229614080
BOARD_SUPER_PARTITION_GROUPS := apple_dynamic_partitions
BOARD_APPLE_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor
BOARD_APPLE_DYNAMIC_PARTITIONS_SIZE := 3229614080

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 1048576

BOARD_ROOT_EXTRA_FOLDERS := apfs hostfs

TARGET_COPY_OUT_VENDOR := vendor
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

# Properties
BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED := true
TARGET_SYSTEM_PROP := $(COMMON_PATH)/system.prop

# Recovery
TARGET_NO_RECOVERY := true

# RIL
ENABLE_VENDOR_RIL_SERVICE := true

# SELinux
BOARD_SEPOLICY_DIRS += $(COMMON_PATH)/sepolicy/common

# Treble
BOARD_VNDK_VERSION := current

# Verified Boot
BOARD_AVB_ENABLE := true

# Wi-Fi
BOARD_WLAN_DEVICE           := brcmfmac
BOARD_HOSTAPD_DRIVER        := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WPA_SUPPLICANT_VERSION      := VER_0_8_X
WIFI_DRIVER_FW_PATH_PARAM   := "/dev/null"
WIFI_DRIVER_FW_PATH_STA     := "/dev/null"
WIFI_DRIVER_FW_PATH_AP      := "/dev/null"
